### ISSUE TITLE
npm run build not working in examples

### ISSUE THREAD

**Issue by ynamite** [alienkitty/alien.js#18]
After following the instructions in the readme I get an error when running npm run build:
```
../src/all.three.js → ../build/alien.three.js...
[!] Error: Could not load /Users/username/Downloads/alien.js/node_modules/@alienkitty/space.js/src/panels/PanelThumbnail.js (imported by ../src/all.three.js): ENOENT: no such file or directory, open '/Users/username/Downloads/alien.js/node_modules/@alienkitty/space.js/src/panels/PanelThumbnail.js'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async /Users/username/Downloads/alien.js/examples/node_modules/rollup/dist/shared/rollup.js:20915:24
    at async Queue.work (/Users/username/Downloads/alien.js/examples/node_modules/rollup/dist/shared/rollup.js:21281:32)
```

**Comment by pschroen** [comment]
Apologies, the `main` branch has gotten out of sync with recent updates from [Space.js](https://github.com/alienkitty/space.js).

In the meantime I've updated the `package.json` to use the latest from the `dev` branch instead.

If you pull the latest and try again it should work now.

```sh
cd alien.js
git reset --hard
git pull
npm i three saharan/OimoPhysics
cd examples
npm i
npm run build
npm start
```

**Comment by ynamite** [comment]
Sweet, thanks for the quick fix! 🚀
